# Generated by Django 2.1.4 on 2018-12-19 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0006_auto_20181219_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentarz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tytul', models.CharField(max_length=200)),
                ('tresc', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('wpis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Wpis')),
            ],
        ),
    ]
