# Generated by Django 2.1.4 on 2018-12-19 11:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181219_0950'),
        ('komentarze', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentarz',
            name='wpis',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='blog.Wpis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='komentarz',
            name='create_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='komentarz',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='komentarz',
            name='tresc',
            field=models.TextField(),
        ),
    ]
