# Generated by Django 2.1.4 on 2018-12-18 13:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpis',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wpis',
            name='modyfied',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
