# Generated by Django 2.1.4 on 2018-12-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpis',
            name='tagi',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
