# Generated by Django 2.1.4 on 2018-12-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_wpis_tagi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='nazwa',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
