# Generated by Django 2.1.4 on 2018-12-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181218_1336'),
        ('blog', '0005_wpis_tagi'),
    ]

    operations = [
    ]
