# Generated by Django 2.1.4 on 2018-12-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_merge_20181219_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='nazwa',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
