# Generated by Django 2.1.4 on 2018-12-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181219_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='nazwa',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
